version: '3'

volumes:
    db_data: {}

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo_flask
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
  web:
    container_name: web
    build: .
    env_file: env/.env
    ports:
      - "5000:5000"
    volumes:
      - .:/webapp